services:

  app:
    image: 'postgres-command-executor:multistage'
    container_name: postgres-command-executor-app
    restart: always
    ports:
      - "8089:8089"
    depends_on:
      - db

  db:
    image: 'postgres:16.2'
    container_name: postgres-command-executor-db
    restart: always
    env_file:
      - path: .env
        required: true
    ports:
      - "5434:5432"

  migrate:
    image: migrate/migrate
    container_name: postgres-command-executor-migrate
    volumes:
      - ./migrations:/migrations
    command: ["-path", "/migrations", "-database", "postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}?sslmode=${POSTGRES_SSL_MODE}", "up"]
    links:
      - db
    depends_on:
      - db