// Code generated by mockery v2.43.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// CommandSaver is an autogenerated mock type for the CommandSaver type
type CommandSaver struct {
	mock.Mock
}

// SaveCommand provides a mock function with given fields: command
func (_m *CommandSaver) SaveCommand(command string) (int64, error) {
	ret := _m.Called(command)

	if len(ret) == 0 {
		panic("no return value specified for SaveCommand")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (int64, error)); ok {
		return rf(command)
	}
	if rf, ok := ret.Get(0).(func(string) int64); ok {
		r0 = rf(command)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(command)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewCommandSaver creates a new instance of CommandSaver. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCommandSaver(t interface {
	mock.TestingT
	Cleanup(func())
}) *CommandSaver {
	mock := &CommandSaver{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
