// Code generated by mockery v2.43.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// CommandDeleter is an autogenerated mock type for the CommandDeleter type
type CommandDeleter struct {
	mock.Mock
}

// DeleteCommand provides a mock function with given fields: id
func (_m *CommandDeleter) DeleteCommand(id int64) error {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteCommand")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(int64) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewCommandDeleter creates a new instance of CommandDeleter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCommandDeleter(t interface {
	mock.TestingT
	Cleanup(func())
}) *CommandDeleter {
	mock := &CommandDeleter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
