// Code generated by mockery v2.43.0. DO NOT EDIT.

package mocks

import (
	uuid "github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// ProcessDeleter is an autogenerated mock type for the ProcessDeleter type
type ProcessDeleter struct {
	mock.Mock
}

// DeleteProcess provides a mock function with given fields: id
func (_m *ProcessDeleter) DeleteProcess(id uuid.UUID) error {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteProcess")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(uuid.UUID) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewProcessDeleter creates a new instance of ProcessDeleter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewProcessDeleter(t interface {
	mock.TestingT
	Cleanup(func())
}) *ProcessDeleter {
	mock := &ProcessDeleter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
